name: Docker-images_with_test
on: push
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Repo-down:
    name: clone repo
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - uses: actions/checkout@v3
    - name: upload le-repo
      uses: actions/upload-artifact@v3
      with:
        name: Le-code
        path: .
  le-build:
    runs-on: ubuntu-latest
    needs: Repo-down
    container: gradle:6-jdk11
    steps:
    - name: get code
      uses: actions/download-artifact@v3
      with:
        name: Le-code
        path: .
    - name: Build-an-app
      run: chmod +x ci/build-app.sh && ci/build-app.sh
    - name: test-an-app  
      run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
    - name: upload repository
      uses: actions/upload-artifact@v3
      with:
        name: Le-code
        path: .
  Docker-image:
    runs-on: ubuntu-latest
    needs: [le-build]
    permissions:
      packages: write
    steps:
    - name: down le-code
      uses: actions/download-artifact@v3
      with:
        name: Le-code
        path: .
    - name: build le-docker
      run: chmod +x ci/build-docker.sh && ci/build-docker.sh
    - name: push le-docker
      run: chmod +x ci/push-docker.sh && ci/push-docker.sh
  Component-test:
    runs-on: ubuntu-latest
    needs: Docker-image
    steps:
    - name: Download code
      uses: actions/download-artifact@v3
      with:
        name: Le-code
        path: .
    - name: Execute component test
      run: chmod +x ci/component-test.sh && ci/component-test.sh
  Performance-test:
    runs-on: ubuntu-latest
    needs: Docker-image
    steps:
    - name: Download code
      uses: actions/download-artifact@v3
      with:
        name: Le-code
        path: .
    - name: Execute performance test
      run: chmod +x ci/performance-test.sh && ci/performance-test.sh